### ISSUE TITLE
Docs for "raf" and "daf" have incorrect links

### ISSUE THREAD

**Issue by janxkoci** [alanrogers/legofit#13]
I noticed in the [main documentation](https://alanrogers.github.io/legofit/html/index.html) that all the links to `daf` and `raf` look like this:

- https://alanrogers.github.io/legofit/html/index.html#daf
- https://alanrogers.github.io/legofit/html/index.html#raf

while at least some of the links should rather be:

- https://alanrogers.github.io/legofit/html/daf.html
- https://alanrogers.github.io/legofit/html/raf.html

In the past (circa last year) most links correctly pointed to the docs for the tools. Now all such links lead to format history description.

I'm not sure which links in the docs should lead to the description of formats in historical context (e.g. "index.html#daf") or the tool (e.g. "daf.html") so I will leave the decision to you. I did not find other wrong links, but I did not do an exhaustive search.

**Comment by alanrogers** [comment]
Thanks for catching this. All the "raf" and "daf" links now point to the main docs for those programs rather than to the paragraphs about them in index.html.
